analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

plugins: 
  riverpod_lint: <latest version from https://pub.dev/packages/riverpod_lint>

linter:
  rules:
    unnecessary_brace_in_string_interps: false